---
- name: Backup gitea dir
  tags: backup
  block:

    - name: Ensure backup gitea dir
      file:
        path: "{{ backup_dir }}/{{ inventory_hostname }}/gitea"
        state: directory
        mode: 0775
        owner: "{{ user }}"
        group: "{{ user }}"
      delegate_to: localhost

    - name: Ensure backup gitea data dir
      file:
        path: "{{ backup_dir }}/{{ inventory_hostname }}/gitea/data"
        state: directory
        mode: 0775
        owner: "{{ user }}"
        group: "{{ user }}"
      delegate_to: localhost

    - name: Ensure backup gitea config dir
      file:
        path: "{{ backup_dir }}/{{ inventory_hostname }}/gitea/config"
        state: directory
        mode: 0775
        owner: "{{ user }}"
        group: "{{ user }}"
      delegate_to: localhost

    - name: Synchronize gitea data to backup drive
      tags: backup
      ansible.posix.synchronize:
        mode: pull
        src: "{{ gitea_data }}"
        dest: "{{ backup_dir }}/{{ inventory_hostname }}/gitea/data"
        recursive: true
        delete: true

    - name: Synchronize gitea config to backup drive
      tags: backup
      ansible.posix.synchronize:
        mode: pull
        src: "{{ gitea_config }}"
        dest: "{{ backup_dir }}/{{ inventory_hostname }}/gitea/config"
        recursive: true
        delete: true
