---
- name: Install Gitea Server
  become: true
  tags: install
  block:

    - name: Add 'gitea' group
      ansible.builtin.group:
        name: gitea
        gid: "{{ gitea_gid }}"
        state: present

    - name: Add Ansible user to gitea
      ansible.builtin.user:
        name: "{{ user }}"
        groups: gitea
        append: true

    - name: Add 'gitea' user
      ansible.builtin.user:
        name: gitea
        uid: "{{ gitea_uid }}"
        group: gitea

    - name: Create config directory
      ansible.builtin.file:
        path: /home/gitea/config
        state: directory
        mode: 0775
        owner: gitea
        group: gitea

    - name: Copy gitea config file
      template:
        src: app.ini.j2
        dest: /home/gitea/config/app.ini
        owner: gitea
        group: gitea
        mode: u=rw,g=,o=

    - name: Create gitea_data volume
      docker_volume:
        driver: "local"
        driver_options:
          type: nfs
          o: "addr={{ nas }},nolock,soft,rw"
          device: "{{ gitea_data_nfs }}"
        volume_name: gitea_data

    - name: Instantiate passwd database
      getent:
        database: passwd

    - name: Create Gitea container
      community.docker.docker_container:
        name: gitea
        image: gitea/gitea:latest-rootless
        pull: true
        user: "{{ gitea_uid }}:{{ gitea_gid }}"
        restart_policy: unless-stopped
        volumes:
          - gitea_data:/var/lib/gitea
          - /home/gitea/config:/etc/gitea
          - /etc/timezone:/etc/timezone:ro
          - /etc/localtime:/etc/localtime:ro
        networks:
          - name: proxy_net
        ports:
          - "2222:2222"

    - name: Allow git SSH
      become: true
      community.general.ufw:
        rule: allow
        port: 2222
      notify: reload ufw
