---
- name: Restore gitea dir
  tags: restore
  block:

    - name: Create data directory
      ansible.builtin.file:
        path: "{{ gitea_data }}"
        state: directory
        mode: 0775
        owner: gitea
        group: development

    - name: Create config directory
      ansible.builtin.file:
        path: "{{ gitea_config }}"
        state: directory
        mode: 0775
        owner: gitea
        group: development

    - name: Restore gitea data
      tags: restore
      ansible.posix.synchronize:
        mode: push
        src: "{{ backup_dir }}/{{ inventory_hostname }}/gitea/data/"
        dest: "{{ gitea_data }}"
        recursive: true
        delete: false

    - name: Restore gitea config
      tags: restore
      ansible.posix.synchronize:
        mode: push
        src: "{{ backup_dir }}/{{ inventory_hostname }}/gitea/config/"
        dest: "{{ gitea_config }}"
        recursive: true
        delete: false
